blank_issues_enabled: true

contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/localcompose/.github/blob/main/docs/strategic-pyramid.md
    about: Please check the documentation before opening an issue.
  - name: ðŸ’¬ Discussions (coming soon ðŸš§)
    # name: ðŸ’¬ Discussions
    url: https://github.com/localcompose
    # url: https://github.com/localcompose/discussions
    about: Discussions will be available soon â€” stay tuned!
    # about: Ask questions and discuss ideas here instead of opening an issue.
  - name: ðŸ§­ Contributing Guide
    url: https://github.com/localcompose/.github/blob/main/CONTRIBUTING.md
    about: Read this before submitting issues or PRs.
